---
- name: Crea Imagen de Contenedor
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vault.yaml
    - ../variables.yaml

  tasks:
  - name: Clona Repositorio Git
    ansible.builtin.git:
      repo: "{{ url_git }}"
      dest: "/tmp/Race-to-the-Cloud-app"

  - name: Login en Registry
    containers.podman.podman_login:
      username: "axmdrz5zetbw/oracleidentitycloudservice/felipe.basso@oracle.com"
      password: 'n3EMpIgUVDs.PE+j0>d;'
      registry: "scl.ocir.io"

  - name: Build and push an image using existing credentials
    containers.podman.podman_image:
      name: "scl.ocir.io/axmdrz5zetbw/ciregistry"
      tag: "latest"
      path: "/tmp/Race-to-the-Cloud-app/"
      push: "yes"
#      push_args:
#        dest: "scl.ocir.io/axmdrz5zetbw"
